version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movietrends
      MYSQL_USER: movietrends
      MYSQL_PASSWORD: Movietrends2198!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://movietrends:Movietrends2198!@movies-trends-db-1:3306/movietrends
